<?php
function t($phrase)
{
  static $translate = array(
    'Welcome To Index' => 'Welcome To Index In Arabic',
    // Header
    'Point Media' => 'بوينت ميديا',
    'Home' => 'الرئيسية',
    'Our Services' => 'خدماتنا',
    'Business Card Design' => 'تصميم كرت الأعمال',
    'Visual Identity Design' => 'تصميم الهوية البصرية',
    'Printing Design' => 'تصميم المطبوعات',
    'Logo Design' => 'تصميم شعار',
    'Adv Design' => 'التصميم الاعلاني',
    'Social Media Design' => 'تصاميم السوشيال ميديا',
    '' => '',
    '' => '',
    'Portfolio' => 'المدونة',
    'About Us' => 'من نحن',
    'Our Works' => 'سابقة أعمالنا',
    'Our Clients' => 'عملائنا',
    'Contact Us' => 'تواصل معنا',
    // Home
    'Get Offer' => 'طلب عرض',
    // Our Services
    'Graphic Design' => 'تصميم جرافيك',
    'Marketing and Advertising' => 'التسويق والإعلان',
    'Non-Profit Services' => 'الخدمات غير الربحية',
    'engineering services' => 'الخدمات الهندسية',
    'Photography and editing' => 'التصوير والمونتاج',
    'Websites development' => 'تطوير مواقع الويب',
    'Translation Services' => 'خدمات الترجمة',
    'Training Courses' => 'الدورات التدريبية',
    'A leading company in the development of commercial and business activities.' => 'شركة رائدة في تطوير الأنشطة التجارية والأعمال. ',
    'Point Media provides its services globally online. Its administrative headquarters are in Syria, and it has sub-centers for service in (Dubai - Abu Dhabi - Cairo - Saudi Arabia).' => 'بوينت ميديا تقدم خدماتها عالمياً أونلاين، مقرها الإداري في سوريا، ولها مراكز فرعية للخدمة في كل من (دبي – أبو ظبي - القاهرة - السعودية).',
    'Here at Point Media, we offer our clients the best services that are loaded with years of experience and hard work. We know the requirements of your business and we know how to put our customers in the forefront through an integrated business plan, starting with designing a visual identity, passing through the design of a distinctive website, then managing digital content, and ending with preparing a marketing plan that gives them a competitive advantage in their markets, and ensures them increase the number of those interested in their business and thus increase in their sales and profits.' => 'نحن هنا في شركة بوينت ميديا نقدم لعملائنا أفضل الخدمات المحملة بخلاصة سنوات من الخبرة والعمل الجاد. نحن نعرف متطلبات نشاطك التجاري ونعرف كيف نجعل عملائنا في الصدارة من خلال خطة عمل متكاملة، بدايةً بتصميم الهوية البصرية مروراً بتصميم موقع الكتروني مميز، ثم إدارة المحتوى الرقمي، وانتهاءً بإعداد خطة تسويقية تمنحهم ميزة تنافسية بأسواقهم، وتضمن لهم زيادة عدد المهتمين بنشاطهم التجاري وبالتالي زيادة في نسب مبيعاتهم وأرباحهم.',
    'Learn about our services and join our training courses today.' => 'تعرَّف على خدماتنا وانضم إلى دوراتنا التدريبية اليوم.',
    // Our Works
    'Our Works' => 'أعمالنا',
    'Visual Identity Design' => 'تصميم هوية بصرية',
    'Logofolio Design' => 'تصميم لوغوفوليو',
    'Social Media Designs' => 'تصاميم سوشال ميديا',
    'Product Photography' => 'تصوير منتجات',
    'Promotional Videos' => 'الفيديوهات الدعائية',
    'See Our Works' => 'تصفح جميع أعمالنا',
    // Our Clients
    'Fadi Kardaghly:' => 'فادي كردغلي:',
    'High morals, commendable efforts, ambitious youth and professional work.' => 'اخلاق عالية، جهود مشكورة، شباب طمموح وعمل احترافي.',
    'Rama Al-Ahmad:' => 'راما الأحمد:',
    'Creative team, demonstrated interest in the success and development of client ideas.' => 'فريق مبدع، واهتمام واضح بنجاح وتطوير أفكار العميل.',
    'Elias Gerges:' => 'الياس جرجس:',
    'I enjoyed the experience with you, I advise the budding entrepreneurs of Point Media to develop your business quickly.' => 'استمتعت بالتجربة معكم، أنصح رواد الأعمال الناشئين بشركة بوينت ميديا لتطوير أعماكم التجارية بسرعة.',
    'Khalil Ibrahim:' => 'خليل إبراهيم:',
    'The training trip with you was very fruitful, I attended a free workshop on managing small and medium enterprises and I will repeat it.' => 'لقد كانت رحلة التدريب معكم مثمرة للغاية، حضرت ورشة مجانية حول إدارة المشاريع الصغيرة والمتوسطة وسأكررها.',
    'Ramadan Younes:' => 'رمضان يونس:',
    'I was pleased to deal with your work team, what I liked most about the quick response, wonderful directions during work and credibility, your services are worth more than the requested price.' => 'سررت بالتعامل مع فريق عملكم، أكثر ما أعجبني الرد السريع والتوجيهات الرائعة أثناء العمل والمصداقية، خدماتكم تستاهل أكثر من السعر المطلوب.',
    'Daher Gerakas:' => 'ضاهر جركس:',
    'Thank you so much for everything you did..a great experience worth repeating.' => 'شكراً جزيلاً على كل ما قدمتموه.. تجربة رائعة تستحق التكرار.',
    'Maysa Bobo:' => 'ميساء بوبو:',
    'Really the most wonderful company and team, I did not expect this professionalism for the required price, I advise everyone to deal with you.' => 'فعلاً أروع شركة وفريق، لم أتوقع هذه الاحترافية بالنسبة للسعر المطلوب، أنصح الجميع بالتعامل معكم.',
    'Ali Tawalo:' => 'علي طوالو:',
    'The beginning of our success was with you, good luck, God willing.' => 'بداية نجاحاتنا كانت معكم، بالتوفيق ان شاء الله.',
    'Our Customers Opinions' => 'آراء عملائنا',
    // Our Blog
    'We Choose For You' => 'اخترنا لكم',
    '3 tips to help you create creative content' => '3 معلومات تساعدك في صناعة محتوى ابداعي',
    'Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the' => 'مرحبًا ، هنا جملة طويلة سيتم اقتطاعها بواسطة Hello هنا جملة طويلة سيتم اقتطاعها بواسطة Hello هنا جملة طويلة سيتم اقتطاعها بواسطة Hello هنا جملة طويلة سيتم اقتطاعها بواسطة Hello هنا هي جملة طويلة سيتم اقتطاعها بواسطة',
    'The Importance Of The Website' => 'أهمية الموقع الإلكتروني',
    'What Is a Brand?!' => 'ما هو البراند ؟!',
    'No Comments' => 'لا توجد تعليقات',
    'Show All Blogs' => 'عرض جميع التدوينات',
    'Read More' => 'تابع القراءة',
    // Why Choose Us
    'Why Choose Us' => 'لماذا تختارنا',
    'Technical support continues until after sales' => 'دعم فني يتواصل ويستمر إلى ما بعد البيع',
    'All services provided to you by Point Media Business Development Company include fast and continuous after-sales technical support to solve any problem related to your project, whether it is design, programming, or managing your marketing campaigns.' => 'كل الخدمات المقدمة لكم من شركة تطوير الأعمال بوينت ميديا تتضمن دعم فني سريع ومستمر لما بعد البيع لحل أي مشكلة تخص مشروعك سواء كان تصميم أو برمجة، أو ادارة حملاتك التسويقية.',
    'A skilled multinational team' => 'فريق بارع مختص متعدد الجنسيات',
    'From designers to developers to writers, our team is equipped with a variety of skills, to provide the best services to our clients.' => 'من المصممين إلى المطورين إلى الكتاب، فريقنا مجهز بمجموعة متنوعة من المهارات، لتقديم أفضل الخدمات لعملائنا.',
    'High quality work' => 'جودة عالية للعمل',
    'We focus on every aspect of our clients needs without leaving anything to chance, as we carry out all our work with the highest expertise, efficiency and speed of delivery.' => 'نحن نركز على كل جانب من جوانب احتياجات عملائنا دون ترك أي شيء للصدفة، إذ ننفذ جميع أعمالنا بأعلى خبرة من الكفاءة والسرعة بالإنجاز.',
    'Regular contact with the trainees' => 'تواصل دوري مع المتدربين',
    'Our team works hard to ensure that all of your questions about the course are answered, free consultations are provided and we keep you updated with the latest developments in the field.' => 'يعمل فريقنا بجد لضمان الإجابة على جميع أسئلتكم حول الدورة التدريبية، وتقديم الاستشارات المجانية وتزويدكم بأحدث المستجدات بالمجال.',
    'Competitive and thoughtful prices' => 'الأسعار المنافسة والمدروسة',
    'Despite the many series of services and providing the best to our customers every time, the prices of our services provided remain within the reasonable range and suitable for everyone.' => 'رغم سلسلة الخدمات العديدة وتقديم الأفضل لعملائنا في كل مرة، إلا أنه تبقى أسعار خدماتنا المقدمة ضمن النطاق المعقول ومناسبة للجميع.',
    // Statistics
    'Point Media Creators' => 'مبدعو بوينت ميديا',
    'Our Clients' => 'عملاؤنا',
    'Experience Years' => 'سنوات خبرة',
    'Presented Services' => 'خدمات مقدمة',
    // Our Team
    'Our Team' => 'فريق عملنا',
    'Ms. Raghad Othman' => 'أ. رغد عثمان',
    'Founder and CEO' => 'المؤسس والمدير التنفيذي',
    'Eng. Aseel Mohammed' => 'م. أسيل محمد',
    'Public Relations Manager' => 'مديرة العلاقات العامة',
    'Mr. Ali Yousef' => 'أ. علي يوسف',
    'Human Resources Manager' => 'مدير الموارد البشرية',
    'Ms. Cindia Imran' => ' أ. سنديا عمران',
    'Training department manager' => 'مديرة قسم التدريب',
    'Mr. Hamza Haroun' => 'أ. حمزة هارون',
    'Customer Service Department Officer' => 'مسؤول قسم خدمة العملاء',
    'Ms. Amira Mahmoud' => 'أ. أميرة محمود',
    'Legal Affairs Director' => 'مديرة الشؤون القانونية',
    'Eng. Amr Othman' => 'م. عمرو عثمان',
    'Programming and development department official' => 'مسؤول قسم البرمجة والتطوير',
    'Eng. Waad Alshea' => 'م. وعد الشيا',
    'Responsible for Digital Marketing and Sales Department' => 'مسؤولة قسم التسويق الرقمي والمبيعات',
    'Eng. Tariq Al-Abdullah' => 'أ. طارق العبد الله',
    'Responsible for Languages and Translation Department' => 'مسؤول قسم اللغات والترجمة',
    'Eng. Karim Hussein' => 'م. كريم حسين',
    'Responsible for advertising design and montage' => 'مسؤول قسم التصميم الإعلاني والمونتاج',
    // Our Hopes
    'If we havent worked together yet... hopefully we will soon' => 'إذا لم نعمل معاً حتى الآن … نأمل أن نفعل ذلك قريباً',
    'Contact Us' => 'تواصل معنا',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    // Footer
    'All Copyright Reserved To ' => 'جميع الحقوق محفوظة لـ',
  );

  if (isset($translate[$phrase])) {
    return $translate[$phrase];
  }
  return $phrase;
}
