<?php
function t($phrase)
{
  static $translate = array(
    'Welcome To Index' => 'Welcome To Index In English',
    // Header
    'Point Media' => 'Point Media',
    'Home' => 'Home',
    'Our Services' => 'Our Services',
    'Business Card Design' => 'Business Card Design',
    'Visual Identity Design' => 'Visual Identity Design',
    'Printing Design' => 'Printing Design',
    'Logo Design' => 'Logo Design',
    'Adv Design' => 'Adv Design',
    'Social Media Design' => 'Social Media Design',
    '' => '',
    '' => '',
    '' => '',
    'Portfolio' => 'Portfolio',
    'About Us' => 'About Us',
    'Our Works' => 'Our Works',
    'Our Clients' => 'Our Clients',
    'Contact Us' => 'Contact Us',
    // Home
    'Get Offer' => 'Get Offer',
    // Our Services
    'Graphic Design' => 'Graphic Design',
    'Marketing and Advertising' => 'Marketing and Advertising',
    'Non-Profit Services' => 'Non-Profit Services',
    'engineering services' => 'engineering services',
    'Photography and editing' => 'Photography and editing',
    'Websites development' => 'Websites development',
    'Translation Services' => 'Translation Services',
    'Training Courses' => 'Training Courses',
    'A leading company in the development of commercial and business activities.' => 'A leading company in the development of commercial and business activities.',
    'Point Media provides its services globally online. Its administrative headquarters are in Syria, and it has sub-centers for service in (Dubai - Abu Dhabi - Cairo - Saudi Arabia).' => 'Point Media provides its services globally online. Its administrative headquarters are in Syria, and it has sub-centers for service in (Dubai - Abu Dhabi - Cairo - Saudi Arabia).',
    'Here at Point Media, we offer our clients the best services that are loaded with years of experience and hard work. We know the requirements of your business and we know how to put our customers in the forefront through an integrated business plan, starting with designing a visual identity, passing through the design of a distinctive website, then managing digital content, and ending with preparing a marketing plan that gives them a competitive advantage in their markets, and ensures them increase the number of those interested in their business and thus increase in their sales and profits.' => 'Here at Point Media, we offer our clients the best services that are loaded with years of experience and hard work. We know the requirements of your business and we know how to put our customers in the forefront through an integrated business plan, starting with designing a visual identity, passing through the design of a distinctive website, then managing digital content, and ending with preparing a marketing plan that gives them a competitive advantage in their markets, and ensures them increase the number of those interested in their business and thus increase in their sales and profits.',
    'Learn about our services and join our training courses today.' => 'Learn about our services and join our training courses today.',
    // Our Works
    'Our Works' => 'Our Works',
    'Visual Identity Design' => 'Visual Identity Design',
    'Logofolio Design' => 'Logofolio Design',
    'Social Media Designs' => 'Social Media Designs',
    'Product Photography' => 'Product Photography',
    'Promotional Videos' => 'Promotional Videos',
    'See Our Works' => 'See Our Works',
    // Our Clients
    'Fadi Kardaghly:' => 'Fadi Kardaghly:',
    'High morals, commendable efforts, ambitious youth and professional work.' => 'High morals, commendable efforts, ambitious youth and professional work.',
    'Rama Al-Ahmad:' => 'Rama Al-Ahmad:',
    'Creative team, demonstrated interest in the success and development of client ideas.' => 'Creative team, demonstrated interest in the success and development of client ideas.',
    'Elias Gerges:' => 'Elias Gerges:',
    'I enjoyed the experience with you, I advise the budding entrepreneurs of Point Media to develop your business quickly.' => 'I enjoyed the experience with you, I advise the budding entrepreneurs of Point Media to develop your business quickly.',
    'Khalil Ibrahim:' => 'Khalil Ibrahim:',
    'The training trip with you was very fruitful, I attended a free workshop on managing small and medium enterprises and I will repeat it.' => 'The training trip with you was very fruitful, I attended a free workshop on managing small and medium enterprises and I will repeat it.',
    'Ramadan Younes:' => 'Ramadan Younes:',
    'I was pleased to deal with your work team, what I liked most about the quick response, wonderful directions during work and credibility, your services are worth more than the requested price.' => '',
    'Daher Gerakas:' => 'Daher Gerakas:',
    'Thank you so much for everything you did..a great experience worth repeating.' => 'Thank you so much for everything you did..a great experience worth repeating.',
    'Maysa Bobo:' => 'Maysa Bobo:',
    'Really the most wonderful company and team, I did not expect this professionalism for the required price, I advise everyone to deal with you.' => 'Really the most wonderful company and team, I did not expect this professionalism for the required price, I advise everyone to deal with you.',
    'Ali Tawalo:' => 'Ali Tawalo:',
    'The beginning of our success was with you, good luck, God willing.' => 'The beginning of our success was with you, good luck, God willing.',
    'Our Customers Opinions' => 'Our Customers Opinions',
    // Our Blog
    'We Choose For You' => 'We Choose For You',
    '3 tips to help you create creative content' => '3 tips to help you create creative content',
    'Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the' => 'Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the Hello here is a long sentence that will be truncated by the',
    'The Importance Of The Website' => 'The Importance Of The Website',
    'What Is a Brand?!' => 'What Is a Brand?!',
    'No Comments' => 'No Comments',
    'Show All Blogs' => 'Show All Blogs',
    'Read More' => 'Read More',
    // Why Choose Us
    'Why Choose Us' => 'Why Choose Us',
    'Technical support continues until after sales' => 'Technical support continues until after sales',
    'All services provided to you by Point Media Business Development Company include fast and continuous after-sales technical support to solve any problem related to your project, whether it is design, programming, or managing your marketing campaigns.' => 'All services provided to you by Point Media Business Development Company include fast and continuous after-sales technical support to solve any problem related to your project, whether it is design, programming, or managing your marketing campaigns.',
    'A skilled multinational team' => 'A skilled multinational team',
    'From designers to developers to writers, our team is equipped with a variety of skills, to provide the best services to our clients.' => 'From designers to developers to writers, our team is equipped with a variety of skills, to provide the best services to our clients.',
    'High quality work' => 'High quality work',
    'We focus on every aspect of our clients needs without leaving anything to chance, as we carry out all our work with the highest expertise, efficiency and speed of delivery.' => 'We focus on every aspect of our clients needs without leaving anything to chance, as we carry out all our work with the highest expertise, efficiency and speed of delivery.',
    'Regular contact with the trainees' => 'Regular contact with the trainees',
    'Our team works hard to ensure that all of your questions about the course are answered, free consultations are provided and we keep you updated with the latest developments in the field.' => 'Our team works hard to ensure that all of your questions about the course are answered, free consultations are provided and we keep you updated with the latest developments in the field.',
    'Competitive and thoughtful prices' => 'Competitive and thoughtful prices',
    'Despite the many series of services and providing the best to our customers every time, the prices of our services provided remain within the reasonable range and suitable for everyone.' => 'Despite the many series of services and providing the best to our customers every time, the prices of our services provided remain within the reasonable range and suitable for everyone.',
    // Statistics
    'Point Media Creators' => 'Point Media Creators',
    'Our Clients' => 'Our Clients',
    'Experience Years' => 'Experience Years',
    'Presented Services' => 'Presented Services',
    // Our Team
    'Our Team' => 'Our Team',
    'Ms. Raghad Othman' => 'Ms. Raghad Othman',
    'Founder and CEO' => 'Founder and CEO',
    'Eng. Aseel Mohammed' => 'Eng. Aseel Mohammed',
    'Public Relations Manager' => 'Public Relations Manager',
    'Mr. Ali Yousef' => 'Mr. Ali Yousef',
    'Human Resources Manager' => 'Human Resources Manager',
    'Ms. Cindia Imran' => 'Ms. Cindia Imran',
    'Training department manager' => 'Training department manager',
    'Mr. Hamza Haroun' => 'Mr. Hamza Haroun',
    'Customer Service Department Officer' => 'Customer Service Department Officer',
    'Ms. Amira Mahmoud' => 'Ms. Amira Mahmoud',
    'Legal Affairs Director' => 'Legal Affairs Director',
    'Eng. Amr Othman' => 'Eng. Amr Othman',
    'Programming and development department official' => 'Programming and development department official',
    'Eng. Waad Alshea' => 'Eng. Waad Alshea',
    'Responsible for Digital Marketing and Sales Department' => 'Responsible for Digital Marketing and Sales Department',
    'Eng. Tariq Al-Abdullah' => 'Eng. Tariq Al-Abdullah',
    'Responsible for Languages and Translation Department' => 'Responsible for Languages and Translation Department',
    'Eng. Karim Hussein' => 'Eng. Karim Hussein',
    'Responsible for advertising design and montage' => 'Responsible for advertising design and montage',
    'If we havent worked together yet... hopefully we will soon' => 'If we haven\'t worked together yet... hopefully we will soon',
    'Contact Us' => 'Contact Us',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    // Footer
    'All Copyright Reserved To ' => 'All Copyright Reserved To ',
  );

  if (isset($translate[$phrase])) {
    return $translate[$phrase];
  }
  return $phrase;
}
